name: GitHub Profile Views Counter CI
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: gayanvoice/github-profile-views-counter-action@master
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
